apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: application
  ports:
  - name: smartoffice-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: room-port
    protocol: TCP
    port: 8081
    targetPort: 8081

