apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-nfs-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.namespace }}-db-nfs-pv

