apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: db
  ports:
  - protocol: TCP
    port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
    nodePort: 30001

