name: Package and Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.6.3

    - name: Package Helm chart
      run: |
        cd smartoffice2.2/qa
        helm package .
        mkdir -p ../../helm-packages
        mv smartoffice2.2-qa-*.tgz ../../helm-packages/

    - name: Checkout charts branch
      uses: actions/checkout@v2
      with:
        ref: charts
        path: charts-branch

    - name: Copy packaged chart to charts branch
      run: |
        cp helm-packages/*.tgz charts-branch/
        cd charts-branch
        helm repo index . --url https://daehanjangaten.github.io/helm

    - name: Commit and push changes
      run: |
        cd charts-branch
        git config --global user.email "83393841+DaeHanJangAten@users.noreply.github.com"
        git config --global user.name "DaeHanJangAten"
        git add .
        git commit -m "Update Helm chart packages"
        git push origin charts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
